num1=input("Enter the first number: ")
num2=input("Enter the second number: ")
sum = int(num1) + int(num2)
product = int(num1) * int(num2)
print("The sum is " + str(sum))
print("The product is " + str(product))